package com.javaforge.project.wizard;

import com.javaforge.project.model.*;
import com.javaforge.project.service.ProjectGeneratorService;
import javafx.geometry.Insets;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.DirectoryChooser;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.File;
import java.nio.file.Path;
import java.util.function.Consumer;

public class ProjectWizard extends Dialog<ProjectConfig> {

    private final TextField nameField = new TextField("demo");
    private final TextField groupIdField = new TextField("com.example");
    private final TextField artifactIdField = new TextField("demo");
    private final TextField packageField = new TextField("com.example.demo");
    private final TextField descriptionField = new TextField("Generated by Java Forge");
    private final TextField outputDirField = new TextField(System.getProperty("user.home") + File.separator + "workspace");
    private final ComboBox<JavaVersion> javaVersionBox = new ComboBox<>();
    private final ComboBox<BuildTool> buildToolBox = new ComboBox<>();
    private final ComboBox<ProjectType> projectTypeBox = new ComboBox<>();
    private final ComboBox<String> databaseBox = new ComboBox<>();
    private final ComboBox<String> serverBox = new ComboBox<>();
    private final CheckBox dockerCheck = new CheckBox("Docker");
    private final CheckBox jwtCheck = new CheckBox("JWT Security");
    private final CheckBox swaggerCheck = new CheckBox("Swagger/OpenAPI");
    private final CheckBox flywayCheck = new CheckBox("Flyway");
    private final CheckBox liquibaseCheck = new CheckBox("Liquibase");
    private final CheckBox junitCheck = new CheckBox("JUnit");
    private final CheckBox mockitoCheck = new CheckBox("Mockito");

    public ProjectWizard() {
        setTitle("New Java Project");
        setHeaderText("Generate a new Java project");
        initModality(Modality.APPLICATION_MODAL);

        DialogPane pane = new DialogPane();
        pane.setContent(buildForm());
        pane.getButtonTypes().addAll(ButtonType.CANCEL, ButtonType.NEXT);

        setDialogPane(pane);
        setResultConverter(button -> button == ButtonType.NEXT ? collectConfig() : null);

        Stage stage = (Stage) getDialogPane().getScene().getWindow();
        stage.setWidth(700);
        stage.setHeight(650);
    }

    private ScrollPane buildForm() {
        GridPane form = new GridPane();
        form.setHgap(10);
        form.setVgap(8);
        form.setPadding(new Insets(20));

        javaVersionBox.getItems().addAll(JavaVersion.values());
        javaVersionBox.setValue(JavaVersion.JAVA_21);

        buildToolBox.getItems().addAll(BuildTool.values());
        buildToolBox.setValue(BuildTool.MAVEN);

        projectTypeBox.getItems().addAll(ProjectType.values());
        projectTypeBox.setValue(ProjectType.SPRING_BOOT);

        databaseBox.getItems().addAll("H2", "PostgreSQL", "MySQL", "Oracle", "SQL Server");
        databaseBox.setValue("H2");

        serverBox.getItems().addAll("Embedded", "Tomcat", "Jetty", "WildFly", "Payara", "GlassFish");
        serverBox.setValue("Embedded");

        Button browseBtn = new Button("Browse...");
        browseBtn.setOnAction(e -> {
            DirectoryChooser chooser = new DirectoryChooser();
            chooser.setTitle("Select Output Directory");
            File dir = chooser.showDialog(getDialogPane().getScene().getWindow());
            if (dir != null) {
                outputDirField.setText(dir.getAbsolutePath());
            }
        });

        HBox dirRow = new HBox(8, outputDirField, browseBtn);
        HBox.setHgrow(outputDirField, Priority.ALWAYS);

        int row = 0;
        form.addRow(row++, new Label("Project Name:"), nameField);
        form.addRow(row++, new Label("Group ID:"), groupIdField);
        form.addRow(row++, new Label("Artifact ID:"), artifactIdField);
        form.addRow(row++, new Label("Package:"), packageField);
        form.addRow(row++, new Label("Description:"), descriptionField);
        form.addRow(row++, new Label("Java Version:"), javaVersionBox);
        form.addRow(row++, new Label("Build Tool:"), buildToolBox);
        form.addRow(row++, new Label("Project Type:"), projectTypeBox);
        form.addRow(row++, new Label("Database:"), databaseBox);
        form.addRow(row++, new Label("Server:"), serverBox);
        form.addRow(row++, new Label("Output Directory:"), dirRow);

        VBox optionsBox = new VBox(6, dockerCheck, jwtCheck, swaggerCheck, flywayCheck, liquibaseCheck, junitCheck, mockitoCheck);
        optionsBox.setPadding(new Insets(10, 0, 0, 0));
        TitledPane optionsTitled = new TitledPane("Options", optionsBox);
        optionsTitled.setExpanded(false);

        form.addRow(row++, optionsTitled);
        GridPane.setColumnSpan(optionsTitled, 2);

        ScrollPane scroll = new ScrollPane(form);
        scroll.setFitToWidth(true);
        return scroll;
    }

    private ProjectConfig collectConfig() {
        ProjectConfig config = new ProjectConfig();
        config.setName(nameField.getText());
        config.setGroupId(groupIdField.getText());
        config.setArtifactId(artifactIdField.getText());
        config.setPackageName(packageField.getText());
        config.setDescription(descriptionField.getText());
        config.setJavaVersion(javaVersionBox.getValue());
        config.setBuildTool(buildToolBox.getValue());
        config.setProjectType(projectTypeBox.getValue());
        config.setDatabase(databaseBox.getValue());
        config.setServer(serverBox.getValue());
        config.setOutputDir(outputDirField.getText());
        config.setDocker(dockerCheck.isSelected());
        config.setJwt(jwtCheck.isSelected());
        config.setSwagger(swaggerCheck.isSelected());
        config.setFlyway(flywayCheck.isSelected());
        config.setLiquibase(liquibaseCheck.isSelected());
        config.setJunit(junitCheck.isSelected());
        config.setMockito(mockitoCheck.isSelected());
        return config;
    }

    public static void showAndGenerate() {
        showAndGenerate(null);
    }

    public static void showAndGenerate(Consumer<Path> onGenerated) {
        ProjectWizard wizard = new ProjectWizard();
        ProjectConfig config = wizard.showAndWait().orElse(null);
        if (config != null) {
            try {
                ProjectGeneratorService service = new ProjectGeneratorService();
                Path path = service.generate(config);
                Alert alert = new Alert(Alert.AlertType.INFORMATION);
                alert.setTitle("Project Generated");
                alert.setHeaderText(null);
                alert.setContentText("Project generated successfully at:\n" + path);
                alert.showAndWait();
                if (onGenerated != null) {
                    onGenerated.accept(path);
                }
            } catch (Exception e) {
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("Error");
                alert.setHeaderText("Failed to generate project");
                alert.setContentText(e.getMessage());
                alert.showAndWait();
            }
        }
    }
}
