package com.javaforge.project.model;

import java.util.ArrayList;
import java.util.List;

public class ProjectConfig {

    private String name = "demo";
    private String groupId = "com.example";
    private String artifactId = "demo";
    private String packageName = "com.example.demo";
    private String description = "Generated by Java Forge";
    private JavaVersion javaVersion = JavaVersion.JAVA_21;
    private BuildTool buildTool = BuildTool.MAVEN;
    private ProjectType projectType = ProjectType.SPRING_BOOT;
    private String server = "embedded";
    private String database = "H2";
    private boolean docker;
    private boolean jwt;
    private boolean swagger;
    private boolean flyway;
    private boolean liquibase;
    private boolean junit;
    private boolean mockito;
    private final List<String> dependencies = new ArrayList<>();
    private String outputDir = System.getProperty("user.dir");

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getGroupId() { return groupId; }
    public void setGroupId(String groupId) { this.groupId = groupId; }
    public String getArtifactId() { return artifactId; }
    public void setArtifactId(String artifactId) { this.artifactId = artifactId; }
    public String getPackageName() { return packageName; }
    public void setPackageName(String packageName) { this.packageName = packageName; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public JavaVersion getJavaVersion() { return javaVersion; }
    public void setJavaVersion(JavaVersion javaVersion) { this.javaVersion = javaVersion; }
    public BuildTool getBuildTool() { return buildTool; }
    public void setBuildTool(BuildTool buildTool) { this.buildTool = buildTool; }
    public ProjectType getProjectType() { return projectType; }
    public void setProjectType(ProjectType projectType) { this.projectType = projectType; }
    public String getServer() { return server; }
    public void setServer(String server) { this.server = server; }
    public String getDatabase() { return database; }
    public void setDatabase(String database) { this.database = database; }
    public boolean isDocker() { return docker; }
    public void setDocker(boolean docker) { this.docker = docker; }
    public boolean isJwt() { return jwt; }
    public void setJwt(boolean jwt) { this.jwt = jwt; }
    public boolean isSwagger() { return swagger; }
    public void setSwagger(boolean swagger) { this.swagger = swagger; }
    public boolean isFlyway() { return flyway; }
    public void setFlyway(boolean flyway) { this.flyway = flyway; }
    public boolean isLiquibase() { return liquibase; }
    public void setLiquibase(boolean liquibase) { this.liquibase = liquibase; }
    public boolean isJunit() { return junit; }
    public void setJunit(boolean junit) { this.junit = junit; }
    public boolean isMockito() { return mockito; }
    public void setMockito(boolean mockito) { this.mockito = mockito; }
    public List<String> getDependencies() { return dependencies; }
    public String getOutputDir() { return outputDir; }
    public void setOutputDir(String outputDir) { this.outputDir = outputDir; }
}
