package com.javaforge.documentation.generator;

import com.javaforge.documentation.model.DocConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.stream.Stream;

public class DocumentationGenerator {

    private static final Logger log = LoggerFactory.getLogger(DocumentationGenerator.class);
    private DocConfig config;
    private Path output;

    public void generate(DocConfig config) throws IOException {
        this.config = config;
        output = Paths.get(config.getProjectDir(), config.getOutputDir());
        Files.createDirectories(output);

        if (config.isGenerateReadme()) generateReadme();
        if (config.isGenerateSwagger()) generateSwagger();
        if (config.isGenerateJavaDoc()) generateJavaDoc();
        if (config.isGenerateUml()) generateUml();
        if (config.isGenerateArchitecture()) generateArchitecture();
        if (config.isGenerateApiDocs()) generateApiDocs();
        if (config.isGenerateDatabaseDoc()) generateDatabaseDoc();

        log.info("Documentation generated at {}", output);
    }

    private void generateReadme() throws IOException {
        String content = String.format(
            "# %s\n\n" +
            "Version: %s\n" +
            "Author: %s\n\n" +
            "## Overview\n\n" +
            "Automated documentation generated by Java Forge IDE.\n\n" +
            "## Build\n\n" +
            "```bash\n" +
            "mvn clean install\n" +
            "```\n\n" +
            "## Run\n\n" +
            "```bash\n" +
            "mvn spring-boot:run\n" +
            "```\n\n" +
            "## License\n\n" +
            "Proprietary - All rights reserved.\n",
            config.getProjectName(), config.getProjectVersion(), config.getAuthor()
        );
        Files.write(output.resolve("README.md"), content.getBytes(StandardCharsets.UTF_8));
    }

    private void generateSwagger() throws IOException {
        Path apiDir = output.resolve("api");
        Files.createDirectories(apiDir);
        String content = String.format(
            "{\n" +
            "  \"openapi\": \"3.0.0\",\n" +
            "  \"info\": {\n" +
            "    \"title\": \"%s API\",\n" +
            "    \"version\": \"%s\",\n" +
            "    \"description\": \"API documentation for %s\"\n" +
            "  },\n" +
            "  \"paths\": {}\n" +
            "}\n",
            config.getProjectName(), config.getProjectVersion(), config.getProjectName()
        );
        Files.write(apiDir.resolve("openapi.json"), content.getBytes(StandardCharsets.UTF_8));
    }

    private void generateJavaDoc() throws IOException {
        Path javadocDir = output.resolve("javadoc");
        Files.createDirectories(javadocDir);
        Path srcDir = Paths.get(config.getProjectDir(), "src/main/java");
        if (Files.exists(srcDir)) {
            try (Stream<Path> files = Files.walk(srcDir).filter(p -> p.toString().endsWith(".java"))) {
                StringBuilder packageDoc = new StringBuilder();
                packageDoc.append("# Java Classes\n\n");
                files.forEach(f -> {
                    try {
                        Path relative = srcDir.relativize(f);
                        String content = String.format(
                            "## %s\n\n```java\n%s\n```\n",
                            relative,
                            new String(Files.readAllBytes(f), StandardCharsets.UTF_8).substring(0, Math.min(500, (int)Files.size(f)))
                        );
                        packageDoc.append(content).append("\n");
                    } catch (IOException ignored) {}
                });
                Files.write(javadocDir.resolve("classes.md"), packageDoc.toString().getBytes(StandardCharsets.UTF_8));
            }
        }
        String index = String.format(
            "<html><body>\n" +
            "<h1>%s - JavaDoc</h1>\n" +
            "<p>Version: %s</p>\n" +
            "<p>Generated by Java Forge IDE</p>\n" +
            "<ul>\n" +
            "  <li><a href=\"classes.md\">Classes</a></li>\n" +
            "</ul>\n" +
            "</body></html>\n",
            config.getProjectName(), config.getProjectVersion()
        );
        Files.write(javadocDir.resolve("index.html"), index.getBytes(StandardCharsets.UTF_8));
    }

    private void generateUml() throws IOException {
        Path umlDir = output.resolve("uml");
        Files.createDirectories(umlDir);
        Path srcDir = Paths.get(config.getProjectDir(), "src/main/java");
        StringBuilder plantUml = new StringBuilder();
        plantUml.append("@startuml\n");
        plantUml.append("title ").append(config.getProjectName()).append(" - Class Diagram\n\n");

        if (Files.exists(srcDir)) {
            try (Stream<Path> files = Files.walk(srcDir).filter(p -> p.toString().endsWith(".java"))) {
                files.forEach(f -> {
                    try {
                        String relative = srcDir.relativize(f).toString().replace('\\', '/');
                        String className = relative.substring(relative.lastIndexOf('/') + 1).replace(".java", "");
                        String pkg = relative.contains("/")
                            ? relative.substring(0, relative.lastIndexOf('/')).replace('/', '.')
                            : "";
                        plantUml.append("class ").append(pkg).append(".").append(className).append(" {}\n");
                    } catch (Exception ignored) {}
                });
            }
        }

        plantUml.append("\n@enduml\n");
        Files.write(umlDir.resolve("class-diagram.puml"), plantUml.toString().getBytes(StandardCharsets.UTF_8));
    }

    private void generateArchitecture() throws IOException {
        Path archDir = output.resolve("architecture");
        Files.createDirectories(archDir);
        String content = String.format(
            "# %s - Architecture\n\n" +
            "## Overview\n\n" +
            "This document describes the architecture of %s.\n\n" +
            "## Layers\n\n" +
            "1. **Presentation Layer** - REST controllers, Web UI\n" +
            "2. **Application Layer** - Services, Use Cases\n" +
            "3. **Domain Layer** - Entities, Value Objects\n" +
            "4. **Infrastructure Layer** - Repositories, Database, External APIs\n\n" +
            "## Technology Stack\n\n" +
            "- Java 21\n" +
            "- Spring Boot\n" +
            "- Maven/Gradle\n" +
            "- PostgreSQL / MySQL / Oracle / SQL Server\n" +
            "- Docker\n\n" +
            "## Modules\n\n" +
            "The project follows a modular monolith pattern:\n\n" +
            "- `core` - Domain entities and business logic\n" +
            "- `api` - REST endpoints\n" +
            "- `persistence` - Database access\n" +
            "- `infrastructure` - External integrations\n\n" +
            "## Security\n\n" +
            "- JWT-based authentication\n" +
            "- Role-based authorization\n" +
            "- HTTPS enforcement\n\n" +
            "## Deployment\n\n" +
            "```yaml\n" +
            "version: '3.8'\n" +
            "services:\n" +
            "  app:\n" +
            "    build: .\n" +
            "    ports:\n" +
            "      - \"8080:8080\"\n" +
            "    environment:\n" +
            "      - SPRING_PROFILES_ACTIVE=prod\n" +
            "```\n",
            config.getProjectName(), config.getProjectName()
        );
        Files.write(archDir.resolve("architecture.md"), content.getBytes(StandardCharsets.UTF_8));
    }

    private void generateApiDocs() throws IOException {
        Path apiDir = output.resolve("api");
        Files.createDirectories(apiDir);
        String content = String.format(
            "# %s - API Reference\n\n" +
            "## Base URL\n\n" +
            "`http://localhost:8080/api`\n\n" +
            "## Endpoints\n\n" +
            "### Health Check\n\n" +
            "```\n" +
            "GET /health\n" +
            "Response: 200 OK\n" +
            "```\n\n" +
            "### Users\n\n" +
            "```\n" +
            "GET    /users       - List all users\n" +
            "POST   /users       - Create user\n" +
            "GET    /users/{id}  - Get user by ID\n" +
            "PUT    /users/{id}  - Update user\n" +
            "DELETE /users/{id}  - Delete user\n" +
            "```\n\n" +
            "## Authentication\n\n" +
            "Use `Authorization: Bearer <token>` header.\n",
            config.getProjectName()
        );
        Files.write(apiDir.resolve("api-reference.md"), content.getBytes(StandardCharsets.UTF_8));
    }

    private void generateDatabaseDoc() throws IOException {
        Path dbDir = output.resolve("database");
        Files.createDirectories(dbDir);
        String content = String.format(
            "# %s - Database Documentation\n\n" +
            "## Schema\n\n" +
            "The database uses the following tables:\n\n" +
            "| Table | Description | Engine |\n" +
            "|-------|-------------|--------|\n" +
            "| users | Application users | InnoDB |\n" +
            "| roles | User roles | InnoDB |\n" +
            "| permissions | Access permissions | InnoDB |\n\n" +
            "## Migrations\n\n" +
            "Managed by Flyway/Liquibase.\n\n" +
            "## ER Diagram\n\n" +
            "See `uml/er-diagram.puml` for the entity-relationship diagram.\n",
            config.getProjectName()
        );
        Files.write(dbDir.resolve("database.md"), content.getBytes(StandardCharsets.UTF_8));
    }
}
